### ISSUE TITLE
Tooltips Mini Toolbars on Context PopUp

### ISSUE THREAD

**Issue by markwilliams1234** [Virtual-TreeView/RibbonFramework#94]
The commands placed on a mini toolbar do not show the tooltips for the command. I notice it does this in Word

**Comment by joachimmarder** [comment]
I never used those mini-toolbars and never saw them in a project that uses the Windows Ribbon Framework, like MS Paint, Windows Explorer or MS Movie Maker.

MS Word does not use the Windows Ribbon Framework, but some custom Ribbon implementation.

Since we have built only a thin wrapper around the Windows Ribbon Framework, I don't think there is much we can do. It would be great if you could supply a sample project that we can add to demo projects, or extend the TextPad sample.

**Comment by joachimmarder** [comment]
Any news on a sample project?

**Comment by joachimmarder** [comment]
No news from reporter => close
